const homeworkWeight = 0.15;
const quizWeight = 0.35;
const testWeight = 0.50;
console.log("Enter three homework grades.");
const homeworkQuestion1 = require("readline-sync");
const homeworkGrade1 = homeworkQuestion1.question();
const homeworkQuestion2 = require("readline-sync");
const homeworkGrade2 = homeworkQuestion2.question();
const homeworkQuestion3 = require("readline-sync");
const homeworkGrade3 = homeworkQuestion3.question();
console.log();
console.log("Enter three quiz grades.");
const quizQuestion1 = require("readline-sync");
const quizGrade1 = quizQuestion1.question();
const quizQuestion2 = require("readline-sync");
const quizGrade2 = quizQuestion2.question();
const quizQuestion3 = require("readline-sync");
const quizGrade3 = quizQuestion3.question();
console.log();
console.log("Enter three test grades.");
const testQuestion1 = require("readline-sync");
const testGrade1 = testQuestion1.question();
const testQuestion2 = require("readline-sync");
const testGrade2 = testQuestion2.question();
const testQuestion3 = require("readline-sync");
const testGrade3 = testQuestion3.question();
console.log();
let homeworkGradeTotal = Number(homeworkGrade1) + Number(homeworkGrade2) + Number(homeworkGrade3);
let homeworkGradeWeighted = homeworkGradeTotal * homeworkWeight;
let quizGradeTotal = Number(quizGrade1) + Number(quizGrade2) + Number(quizGrade3);
let quizGradeWeighted = quizGradeTotal * quizWeight;
let testGradeTotal = Number(testGrade1) + Number(testGrade2) + Number(testGrade3);
let testGradeWeighted = testGradeTotal * testWeight;
let markingPeriodGrade = Number(homeworkGradeWeighted) + Number(quizGradeWeighted) + Number(testGradeWeighted);
console.log("Your marking period grade is "markingPeriodGrade.toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2}) + "%.");
